apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: spark-master
  ports:
  - protocol: TCP
    port: 7077
    targetPort: app-port
