apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark-executor
spec:
  replicas: 1
  template:
    metadata:
      name: spark-executor
      labels:
        case: spark-executor
    spec:
      containers:
        - name: spark-executor
          image: mikelangelo/spark-executor
          imagePullPolicy : IfNotPresent
