apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      name: spark-worker
      labels:
        case: spark-worker
      annotations:
        kubernetes.io/target-runtime: virtlet
        VirtletDiskDriver: virtio
        VirtletCloudInitUserDataScript: |
          run:
            - POST: /env/MASTER
              val: spark-master.default.svc.cluster.local:7077
            - PUT: /app/
              command: "runscript /run/worker"
    spec:
      affinity: {"nodeAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": {"nodeSelectorTerms": [{"matchExpressions": [{"key": "extraRuntime", "operator": "In", "values": ["virtlet"]}]}]}}}
      containers:
        - name: spark-worker
          image: virtlet/image-service.kube-system/spark.qemu
          resources:
            limits:
              memory: 3000Mi
